{{- range $patternName, $app := .Values.qeCIPipelines.patterns }}
  {{- $flavors := include "qeCIPipelines.supportedFlavors" (dict
        "root" $
        "app" $app
      ) | fromJson }}
  {{- $ocpVersions := include "tekton.supportedOcpVersions" (dict
        "root" $
        "app" $app
      ) | fromJson }}
  {{- range $flavorName, $flavorCfg := $flavors }}
    {{- $platforms := include "qeCIPipelines.supportedPlatformsForFlavor" (dict
          "root" $
          "app" $app
          "flavorName" $flavorName
          "flavorCfg" $flavorCfg
        ) | fromJson }}
    {{- range $platformName, $_ := $platforms }}
      {{- range $ocpVersion, $_ := $ocpVersions }}
        {{- $ctx := dict
              "root" $
              "app" $app
              "patternName" $patternName
              "platformName" $platformName
              "ocpVersion" $ocpVersion
              "flavorName" $flavorName
              "flavorCfg" $flavorCfg
              "repo" (default "" $app.repo)
              "namespace" $.Values.qeCIPipelines.defaults.namespace
            }}
---
apiVersion: v1
kind: Configmap
metadata:
  name: {{ printf "%s-%s-%s-%s" $patternName $platformName ($ocpVersion | replace "." "-") $flavorName }}
  labels:
    pattern.name: {{ $patternName }}
    pattern.platform: {{ $platformName }}
    pattern.ocp-version: {{ $ocpVersion | replace "." "-" }}
    pattern.flavor: {{ $flavorName }}
spec:
  data:
    clusterGroup: {{ include "qeCIPipelines.targetClusterGroup" $ctx | quote }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}